title: Welcome, Musicophiles
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Music is a universal language. It's a form of communication that transcends space and time, touching the hearts of people worldwide

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
